trigger:
- main

pool:
  vmImage: windows-latest

variables:
  CodeQL.Enabled: true
  LGTM.UploadSnapshot: false

steps:
#####################################################
# Credential Scanner
#####################################################
- task: CredScan@3
#####################################################


#####################################################
# CodeQL
#####################################################
- task: Semmle@1
  inputs:
    sourceCodeDirectory: '$(Build.SourcesDirectory)'
    language: 'python'
    querySuite: 'Recommended'
    timeout: '1800'
    ram: '16384'
    addProjectDirToScanningExclusionList: true
#####################################################

#####################################################
# Component Governance
#####################################################
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'
#####################################################

#####################################################
# Public Security Tools builds artifacts
#####################################################
- task: PublishSecurityAnalysisLogs@3
  inputs:
    ArtifactName: 'CodeAnalysisLogs'
    ArtifactType: 'Container'
    PublishProcessedResults: true
    AllTools: true
    ToolLogsNotFoundAction: 'Standard'
#####################################################

